stages:
    - dev
    - build

variables:
    REGISTRY: ${CI_REGISTRY}/deworkerpro/demo-auction
    IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:1.26.0
    services:
        - docker:19.03-dind
    before_script:
        - apk add --no-cache make
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - api/vendor/
            - frontend/node_modules/
            - cucumber/node_modules/
    script:
        - make init
        - make push-dev-cache

        - make api-validate-schema

        - make api-lint
        - make frontend-lint
        - make cucumber-lint

        - make api-analyze

        - make api-test
        - make frontend-test
    artifacts:
        paths:
            - api/var/log

build:
    stage: build
    only:
        - branches
    image: docker/compose:1.26.0
    services:
        - docker:19.03-dind
    before_script:
        - apk add --no-cache make
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - make build
        - make push-build-cache
