services:
    traefik:
        image: traefik:3.6
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    frontend:
        image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}
        environment:
            NGINX_UPSTREAM_RESOLVER: 127.0.0.11
            NGINX_UPSTREAM_HOST: ""
            VITE_AUTH_URL: http://api.localhost
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
            - traefik.http.routers.frontend.entryPoints=http
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www\.localhost/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    api:
        image: ${REGISTRY}/auction-api:${IMAGE_TAG}
        environment:
            NGINX_UPSTREAM_RESOLVER: 127.0.0.11
            NGINX_UPSTREAM_HOST: ""
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api.rule=Host(`api.localhost`)
            - traefik.http.routers.api.entryPoints=http
            - traefik.http.services.api.loadBalancer.server.port=80

    api-php-fpm:
        image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock:8080/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock:8080/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET: yandex-secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET: mailru-secret
        secrets:
            - jwt_public_key
            - jwt_private_key

    api-php-cli:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock:8080/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock:8080/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET: yandex-secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET: mailru-secret
        secrets:
            - jwt_public_key
            - jwt_private_key

    testing-api-php-cli:
        image: ${REGISTRY}/auction-testing-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: http://api.localhost
            OAUTH_YANDEX_AUTH_URL: http://wiremock.localhost/oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: http://wiremock:8080/oauth.yandex.ru
            OAUTH_YANDEX_API_URL: http://wiremock:8080/login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: app
            OAUTH_YANDEX_CLIENT_SECRET: yandex-secret
            OAUTH_MAILRU_AUTH_URL: http://wiremock.localhost/oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_API_URL: http://wiremock:8080/oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: app
            OAUTH_MAILRU_CLIENT_SECRET: mailru-secret
        secrets:
            - jwt_public_key
            - jwt_private_key

    api-postgres:
        image: postgres:17.7-alpine3.23
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app

    mailer:
        image: axllent/mailpit:v1.27
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    wiremock:
        image: wiremock/wiremock:3x-alpine
        networks:
            - traefik-public
            - default
        volumes:
            - ./wiremock:/home/wiremock
        command:
            - '--global-response-templating'
            - '--verbose'
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.wiremock.rule=Host(`wiremock.localhost`)
            - traefik.http.services.wiremock.loadBalancer.server.port=8080
            - traefik.http.routers.wiremock.entryPoints=http

    cucumber-node-cli:
        image: ${REGISTRY}/auction-cucumber-node-cli:${IMAGE_TAG}
        volumes:
            - ./cucumber/var:/app/var
        network_mode: service:traefik

secrets:
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key

networks:
    traefik-public:
        name: traefik-public
