version: "3.9"
services:
    cron:
        image: crazymax/swarm-cronjob:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            LOG_LEVEL: info
        deploy:
            placement:
                constraints: [ node.role == manager ]

    frontend:
        image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}
        environment:
            VITE_AUTH_URL: https://api.demo-auction.deworker.pro
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.frontend.rule=Host(`demo-auction.deworker.pro`) || Host(`www.demo-auction.deworker.pro`)
                - traefik.http.services.frontend.loadBalancer.server.port=80
                - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www\.demo-auction\.deworker\.pro/(.*)$$
                - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}demo-auction.deworker.pro/$${2}
                - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
                - traefik.http.routers.frontend.middlewares=frontend-redirect,secure-headers
                - traefik.http.routers.frontend.entryPoints=https
                - traefik.http.routers.frontend.tls=true
                - traefik.http.routers.frontend.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    api:
        image: ${REGISTRY}/auction-api:${IMAGE_TAG}
        networks:
            - traefik-public
            - default
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.api.rule=Host(`api.demo-auction.deworker.pro`)
                - traefik.http.services.api.loadBalancer.server.port=80
                - traefik.http.routers.api.middlewares=secure-headers
                - traefik.http.routers.api.entryPoints=https
                - traefik.http.routers.api.tls=true
                - traefik.http.routers.api.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    api-php-fpm:
        image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USERNAME: ${API_MAILER_USERNAME}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://demo-auction.deworker.pro
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: https://api.demo-auction.deworker.pro
            OAUTH_YANDEX_AUTH_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_API_URL: https://login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
            OAUTH_YANDEX_CLIENT_SECRET: ${OAUTH_YANDEX_CLIENT_SECRET}
            OAUTH_MAILRU_AUTH_URL: https://oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: https://oauth.mail.ru
            OAUTH_MAILRU_API_URL: https://oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: ${OAUTH_MAILRU_CLIENT_ID}
            OAUTH_MAILRU_CLIENT_SECRET: ${OAUTH_MAILRU_CLIENT_SECRET}
        secrets:
            - jwt_public_key
            - jwt_private_key
        deploy:
            mode: replicated
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s

    api-migration:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USERNAME: ${API_MAILER_USERNAME}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://demo-auction.deworker.pro
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: https://api.demo-auction.deworker.pro
            OAUTH_YANDEX_AUTH_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_API_URL: https://login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
            OAUTH_YANDEX_CLIENT_SECRET: ${OAUTH_YANDEX_CLIENT_SECRET}
            OAUTH_MAILRU_AUTH_URL: https://oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: https://oauth.mail.ru
            OAUTH_MAILRU_API_URL: https://oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: ${OAUTH_MAILRU_CLIENT_ID}
            OAUTH_MAILRU_CLIENT_SECRET: ${OAUTH_MAILRU_CLIENT_SECRET}
        secrets:
            - jwt_public_key
            - jwt_private_key
        command: ["sh", "-c", "wait-for-it api-postgres:5432 -t 60 && exec php bin/app.php migrations:migrate --no-interaction"]
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 120s

    api-oauth-clear-expired:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: ${API_DB_PASSWORD}
            DB_NAME: app
            MAILER_HOST: ${API_MAILER_HOST}
            MAILER_PORT: ${API_MAILER_PORT}
            MAILER_USERNAME: ${API_MAILER_USERNAME}
            MAILER_PASSWORD: ${API_MAILER_PASSWORD}
            MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
            FRONTEND_URL: https://demo-auction.deworker.pro
            SENTRY_DSN: ""
            JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
            OAUTH_CALLBACK_URL: https://api.demo-auction.deworker.pro
            OAUTH_YANDEX_AUTH_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_TOKEN_URL: https://oauth.yandex.ru
            OAUTH_YANDEX_API_URL: https://login.yandex.ru
            OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
            OAUTH_YANDEX_CLIENT_SECRET: ${OAUTH_YANDEX_CLIENT_SECRET}
            OAUTH_MAILRU_AUTH_URL: https://oauth.mail.ru
            OAUTH_MAILRU_TOKEN_URL: https://oauth.mail.ru
            OAUTH_MAILRU_API_URL: https://oauth.mail.ru
            OAUTH_MAILRU_CLIENT_ID: ${OAUTH_MAILRU_CLIENT_ID}
            OAUTH_MAILRU_CLIENT_SECRET: ${OAUTH_MAILRU_CLIENT_SECRET}
        secrets:
            - jwt_public_key
            - jwt_private_key
        command: ["sh", "-c", "wait-for-it api-postgres:5432 -t 60 && exec php bin/app.php oauth:clear-expired"]
        deploy:
            labels:
                - swarm.cronjob.enable=true
                - swarm.cronjob.schedule=0 * * * *
                - swarm.cronjob.skip-running=true
            replicas: 0
            restart_policy:
                condition: none

    api-postgres:
        image: postgres:17.7-alpine3.23
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${API_DB_PASSWORD}
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        deploy:
            placement:
                constraints: [ node.labels.db == db ]
            endpoint_mode: dnsrr

    api-postgres-backup:
        image: ${REGISTRY}/auction-api-postgres-backup:${IMAGE_TAG}
        environment:
            BACKUP_NAME: auction_api-postgres
            POSTGRES_HOST: api-postgres
            POSTGRES_USERNAME: app
            POSTGRES_PASSWORD: ${API_DB_PASSWORD}
            POSTGRES_DB: app
            AWS_ACCESS_KEY_ID: ${BACKUP_AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${BACKUP_AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${BACKUP_AWS_DEFAULT_REGION}
            S3_ENDPOINT: ${BACKUP_S3_ENDPOINT}
            S3_BUCKET: ${BACKUP_S3_BUCKET}
        volumes:
            - api-postgres-backup:/app
        command: ["sh", "-c", "wait-for-it api-postgres:5432 -t 60 && exec backup"]
        deploy:
            labels:
                - swarm.cronjob.enable=true
                - swarm.cronjob.schedule=0 * * * *
                - swarm.cronjob.skip-running=true
            replicas: 0
            restart_policy:
                condition: none

secrets:
    jwt_public_key:
        file: ${JWT_PUBLIC_KEY_FILE}
    jwt_private_key:
        file: ${JWT_PRIVATE_KEY_FILE}

volumes:
    api-postgres:
    api-postgres-backup:

networks:
    traefik-public:
        external: true
