name: Pipeline

on: push

env:
    REGISTRY: docker.pkg.github.com/deworkerpro/demo-auction
    REGISTRY_HOST: docker.pkg.github.com

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache API composer
                uses: actions/cache@v2
                with:
                    path: api/vendor
                    key: api-composer-${{ hashFiles('api/composer.lock') }}

            -   name: Cache frontend yarn
                uses: actions/cache@v2
                with:
                    path: frontend/node_modules
                    key: frontend-yarn-${{ hashFiles('frontend/yarn.lock') }}

            -   name: Cache cucumber yarn
                uses: actions/cache@v2
                with:
                    path: cucumber/node_modules
                    key: cucumber-yarn-${{ hashFiles('cucumber/yarn.lock') }}

            -   name: Docker login
                uses: azure/docker-login@v1
                with:
                    login-server: ${{ env.REGISTRY_HOST }}
                    username: ElisDN
                    password: ${{ github.token }}

            -   name: Dev Init
                run: make init

            -   name: Push dev cache images
                run: make push-dev-cache

            -   name: Validate
                run: make api-validate-schema

            -   name: Lint API
                run: make api-lint

            -   name: Lint Frontend
                run: make frontend-lint

            -   name: Lint Cucumber
                run: make cucumber-lint

            -   name: Analyze API
                run: make api-analyze

            -   name: Test API
                id: api-test
                run: make api-test

            -   name: Archive tests output
                uses: actions/upload-artifact@v1
                with:
                    name: test-output
                    path: api/var/log
                if: ${{ always() && steps.api-test.outcome == 'failure' }}

            -   name: Test Frontend
                run: make frontend-test

            -   name: Dev Down
                run: make docker-down-clear

            -   name: Inject branch slug
                uses: rlespinasse/github-slug-action@v2.x

            -   name: Set image tag
                run: echo "::set-env name=IMAGE_TAG::${{ env.GITHUB_REF_SLUG }}-${GITHUB_RUN_NUMBER}"

            -   name: Build
                run: make build

            -   name: Push build cache images
                run: make push-build-cache

            -   name: Testing Build
                run: make testing-build

            -   name: Testing Init
                run: make testing-init

            -   name: Testing Smoke
                run: make testing-smoke

            -   name: Testing E2E
                run: make testing-e2e

            -   name: Testing Down
                run: make testing-down-clear
