name: Pipeline

on:
    push:
        branches:
            - master

env:
    REGISTRY: ${{ secrets.REGISTRY }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache API composer
                uses: actions/cache@v2
                with:
                    path: api/vendor
                    key: api-composer-${{ hashFiles('api/composer.lock') }}

            -   name: Cache frontend yarn
                uses: actions/cache@v2
                with:
                    path: frontend/node_modules
                    key: frontend-yarn-${{ hashFiles('frontend/yarn.lock') }}

            -   name: Cache cucumber yarn
                uses: actions/cache@v2
                with:
                    path: cucumber/node_modules
                    key: cucumber-yarn-${{ hashFiles('cucumber/yarn.lock') }}

            -   name: Docker login
                uses: azure/docker-login@v1
                with:
                    login-server: ${{ secrets.REGISTRY }}
                    username: ${{ secrets.REGISTRY_USER }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}

            -   name: Dev Init
                run: make init
